name: Build Docker image (backend)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-build:
    name: Build Docker image (backend)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend Docker image
        working-directory: ./backend
        run: |
          docker build -t ai-project-manager-backend:latest .
          docker save ai-project-manager-backend:latest -o backend-image.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-image
          path: backend/backend-image.tar

      - name: Optionally push to registry
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
        run: |
          if [ -z "$DOCKER_USERNAME" ] || [ -z "$DOCKER_PASSWORD" ]; then
            echo "DOCKER credentials not set; skipping push"
            exit 0
          fi
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin ${DOCKER_REGISTRY:-docker.io}
          IMAGE_TAG=${DOCKER_REGISTRY:-docker.io}/$DOCKER_USERNAME/ai-project-manager-backend:latest
          docker tag ai-project-manager-backend:latest $IMAGE_TAG
          docker push $IMAGE_TAG
